git-cache: never generate an empty string for a canonical url
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/bin/git-cache b/bin/git-cache
--- a/bin/git-cache
+++ b/bin/git-cache
@@ -451,7 +451,12 @@ full_url () {
                 break
             fi
         done
-        echo "$(canonical_url "$url")"
+        new_url="$(canonical_url "$url")"
+        if [ -z "$new_url" ]; then
+            echo >&2 "Error: $url was translated to an empty string"
+            exit 1
+        fi
+        echo "$new_url"
     }
 }
 
