tmx: fix old session cleanup

diff --git a/bin/tmx b/bin/tmx
--- a/bin/tmx
+++ b/bin/tmx
@@ -37,7 +37,8 @@ gen_session_id() {
     elif which sha1sum >/dev/null 2>&1; then
         echo $datetime | sha1sum - | cut -c1-4
     else
-        echo $datetime
+        echo >&2 "No checksum tool found, aborting"
+        exit 3
     fi
 }
 
@@ -51,14 +52,14 @@ else
     # Make sure we are not already in a tmux session
     if [[ -z "$TMUX" ]]; then
         # Kill defunct sessions first
-        old_sessions=$(tmux ls 2>/dev/null | egrep "^[0-9]{14}.*[0-9]+\)$" | cut -f 1 -d:)
+        old_sessions=$(tmux ls 2>/dev/null | egrep "^$base_session-[0-9a-z]{4}:" | cut -f 1 -d:)
         for old_session_id in $old_sessions; do
             tmux kill-session -t $old_session_id
         done
 
         echo "Launching copy of base session $base_session ..."
         # Session is is date and time to prevent conflict
-        session_id=`gen_session_id`
+        session_id="$base_session-`gen_session_id`"
         # Create a new session (without attaching it) and link to base session
         # to share windows
         tmux new-session -d -t $base_session -s $session_id
