Greatly simplify the existing bindir script

diff --git a/home/.chezmoiscripts/posix/run_once_before_existing_bindir b/home/.chezmoiscripts/posix/run_once_before_existing_bindir
--- a/home/.chezmoiscripts/posix/run_once_before_existing_bindir
+++ b/home/.chezmoiscripts/posix/run_once_before_existing_bindir
@@ -2,16 +2,19 @@
 
 set -euo pipefail
 
-if ! [ -e ~/bin/.git ]; then
-    if ! [ -d ~/bin ]; then
-        git clone --depth 1 https://github.com/kergoth/scripts ~/bin
-    else
-        (
-            cd ~/bin || exit 1
-            git init
-            git remote add origin https://github.com/kergoth/scripts
-            git fetch --depth=1 origin main
-            git checkout --force -b main origin/main
-        ) || { rm -rf ~/bin/.git; exit 1; }
-    fi
+if [ -d ~/bin ] && ! [ -e ~/bin/.git ]; then
+    (
+        cd ~/bin || exit 1
+        if ! command -v git &>/dev/null; then
+            echo >&2 "Error: git not found, exiting"
+            exit 1
+        fi
+        git init
+        git remote add origin https://github.com/kergoth/scripts
+        git fetch --depth=1 origin main
+        git checkout --force -b main origin/main
+    ) || {
+        rm -rf ~/bin/.git
+        exit 1
+    }
 fi
