home-manager: fix modules install *and* obeying flake.lock

diff --git a/home/.chezmoiscripts/posix/run_onchange_before_20_configure-home-manager.tmpl b/home/.chezmoiscripts/posix/run_onchange_before_20_configure-home-manager.tmpl
--- a/home/.chezmoiscripts/posix/run_onchange_before_20_configure-home-manager.tmpl
+++ b/home/.chezmoiscripts/posix/run_onchange_before_20_configure-home-manager.tmpl
@@ -11,26 +11,40 @@
 
 set -euo pipefail
 
-for file in nix/nix.conf.tmpl home-manager/home.nix.tmpl \
-            home-manager/flake.nix.tmpl home-manager/private_flake.lock; do
-    src="$CHEZMOI_SOURCE_DIR/dot_config/$file"
-    dest="$CHEZMOI_HOME_DIR/.config/${file%.tmpl}"
-    if ! [ -e "$dest" ] || [ "$src" -nt "$dest" ]; then
-        mkdir -p "$(dirname "$dest")"
+find "$CHEZMOI_SOURCE_DIR/dot_config/home-manager" -name \*.nix -o -name \*.nix.tmpl -o -name \*.lock |
+    while read -r src; do
+        file="${src#"$CHEZMOI_SOURCE_DIR/dot_config/"}"
+        dest="$CHEZMOI_HOME_DIR/.config/${file%.tmpl}"
         case "$file" in
-        *.tmpl)
-            chezmoi execute-template <"$src" >"$dest" || {
-                rm -f "$dest"
-                echo >&2 "Error processing chezmoi template $src"
-                exit 1
-            }
-            ;;
-        *)
-            cp -af "$src" "$dest"
-            ;;
+            */private_*)
+                private=1
+                base=$(basename "$dest")
+                dest="$(dirname "$dest")/${base#private_}"
+                ;;
+            *)
+                private=0
+                ;;
         esac
-    fi
-done
+
+        if ! [ -e "$dest" ] || [ "$src" -nt "$dest" ]; then
+            mkdir -p "$(dirname "$dest")"
+            case "$file" in
+            *.tmpl)
+                chezmoi execute-template <"$src" >"$dest" || {
+                    rm -f "$dest"
+                    echo >&2 "Error processing chezmoi template $src"
+                    exit 1
+                }
+                if [ "$private" -eq 1 ]; then
+                    chmod go-rwx "$dest"
+                fi
+                ;;
+            *)
+                cp -af "$src" "$dest"
+                ;;
+            esac
+        fi
+    done
 
 echo >&2 "Applying home manager configuration"
 export USER="${USER:-${LOGNAME:-$(whoami)}}"
