Ensure that a chezmoi execute-template failure doean't leave remnants

diff --git a/home/.chezmoiscripts/posix/run_onchange_before_nix.tmpl b/home/.chezmoiscripts/posix/run_onchange_before_nix.tmpl
--- a/home/.chezmoiscripts/posix/run_onchange_before_nix.tmpl
+++ b/home/.chezmoiscripts/posix/run_onchange_before_nix.tmpl
@@ -17,7 +17,11 @@ for file in home.nix.tmpl flake.nix.tmpl flake.lock; do
     if ! [ -e "$dest" ] || [ "$src" -nt "$dest" ]; then
         case "$file" in
         *.tmpl)
-            chezmoi execute-template <"$src" >"$dest"
+            chezmoi execute-template <"$src" >"$dest" || {
+                rm -f "$dest"
+                echo >&2 "Error processing chezmoi template $src"
+                exit 1
+            }
             ;;
         *)
             cp -af "$src" "$dest"
