brewfile-diff-installed: add -c/-f args

diff --git a/scripts/extras/brewfile-diff-installed b/scripts/extras/brewfile-diff-installed
--- a/scripts/extras/brewfile-diff-installed
+++ b/scripts/extras/brewfile-diff-installed
@@ -3,33 +3,58 @@
 
 # Usage: ./brewfile-diff-installed Brewfile
 
-# Exit on error
 set -e
 
-# Check for Brewfile
-if [ -z "$1" ]; then
-  echo "Usage: ./brewfile-diff-installed Brewfile"
-  exit 1
+usage() {
+    echo >&2 "${0##*/} [options] Brewfile"
+    exit 2
+}
+
+formula=
+cask=
+while getopts fch opt; do
+    case "$opt" in
+    f)
+        formula=1
+        ;;
+    c)
+        cask=1
+        ;;
+    \? | h)
+        usage
+        ;;
+    esac
+done
+shift $((OPTIND - 1))
+
+if [ -z "$formula" ] && [ -z "$cask" ]; then
+    cask=1
+    formula=1
 fi
 
-# Check for Brew
-if ! command -v brew &> /dev/null; then
-  echo "Homebrew is not installed."
-  exit 1
+if [ $# -eq 0 ]; then
+    usage
 fi
 
-# Check for Brewfile
 if [ ! -f "$1" ]; then
-  echo "Brewfile not found."
-  exit 1
+    echo "Brewfile not found."
+    exit 1
+fi
+
+if ! command -v brew &>/dev/null; then
+    echo "Homebrew is not installed."
+    exit 1
 fi
 
 # Get installed packages
-installed=$(brew list)
+if [ -n "$formula" ] && [ -n "$cask" ]; then
+    installed=$(brew list)
+else
+    installed=$(brew list ${formula:+--formula} ${cask:+--cask})
+fi
 
 # Get listed packages
-listed=$(brew bundle list --formula --cask --file="$1")
-
+listed=$(brew bundle list ${formula:+--formula} ${cask:+--cask} --file="$1")
 
 diff_highlight() {
     if [ -t 1 ]; then
