git-clone-via: fix error message when destination already exists
Signed-off-by: Chris Larson <chris_larson@mentor.com>

diff --git a/git-clone-via b/git-clone-via
--- a/git-clone-via
+++ b/git-clone-via
@@ -113,7 +113,7 @@ mirror=0
 process_arguments "$@"
 
 if [ -e "$to" ]; then
-    echo >&2 "Error: $dest already exists, aborting"
+    echo >&2 "Error: $to already exists, aborting"
     exit 3
 fi
 
