git-cache: clone: die early if dest already exists
Signed-off-by: Chris Larson <chris_larson@mentor.com>

diff --git a/git-cache b/git-cache
--- a/git-cache
+++ b/git-cache
@@ -113,6 +113,10 @@ cmd_clone () {
     if [ -z "$destination" ]; then
         destination=$PWD/$basename
     fi
+    if [ -d "$destination" ]; then
+        die "Error: $destination already exists"
+        exit 3
+    fi
     cache_repo="$cache_dir/$basename.git"
     remote="$(hash "$cache_url")"
 
