zsh: ensure that we're in emacs mode, not vi
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/install b/install
--- a/install
+++ b/install
@@ -28,6 +28,32 @@ set_launchd () {
     fi
 }
 
+should_replace () {
+    if ! [ -e "$1" ] && ! [ -L "$1" ]; then
+        return 0
+    fi
+
+    if [ $force -eq 0 ]; then
+        while true; do
+            read -n 1 -p "Replace existing $1? [Y|n] " will_continue
+            printf "\n"
+            case "$will_continue" in
+                [yY]|"")
+                    return 0
+                    ;;
+                [nN])
+                    return 1
+                    ;;
+                *)
+                    echo >&2 "Invalid input '$will_continue'"
+                    ;;
+            esac
+        done
+    else
+        return 1
+    fi
+}
+
 link () {
     # Link a file to a destination using a relative path, with particular
     # convenience handling for dotfiles. ex.:
@@ -119,7 +145,7 @@ normalize_path()
 }
 
 install_templated () {
-    # Extremely basic template flie generation, currently only implements
+    # Extremely basic template file generation, currently only implements
     # %include, which does what you would expect
     dotfile_dest="$2"
     destdir="${dotfile_dest%/*}"
