Revert "Update externals"
This reverts commit 81bff8a5a7d7b897f1bd358692c3652e98585a78.

diff --git a/rust/scripts/rustup b/rust/scripts/rustup
--- a/rust/scripts/rustup
+++ b/rust/scripts/rustup
@@ -13,16 +13,14 @@
 # install rustup. It just does platform detection, downloads the installer
 # and runs it.
 
-if [ -z "$RUSTUP_UPDATE_ROOT" ]; then
-    RUSTUP_UPDATE_ROOT="https://static.rust-lang.org/rustup"
-fi
-
 set -u
+
+RUSTUP_UPDATE_ROOT="https://static.rust-lang.org/rustup/dist"
 
 #XXX: If you change anything here, please make the same changes in setup_mode.rs
 usage() {
     cat 1>&2 <<EOF
-rustup-init 1.17.0 (edb52ac60 2019-03-05)
+rustup-init 1.0.0 (408ed84 2017-02-11)
 The installer for rustup
 
 USAGE:
@@ -62,11 +60,10 @@ main() {
             ;;
     esac
 
-    local _url="${RUSTUP_UPDATE_ROOT}/dist/${_arch}/rustup-init${_ext}"
+    local _url="$RUSTUP_UPDATE_ROOT/$_arch/rustup-init$_ext"
 
-    local _dir
-    _dir="$(mktemp -d 2>/dev/null || ensure mktemp -d -t rustup)"
-    local _file="${_dir}/rustup-init${_ext}"
+    local _dir="$(mktemp -d 2>/dev/null || ensure mktemp -d -t rustup)"
+    local _file="$_dir/rustup-init$_ext"
 
     local _ansi_escapes_are_valid=false
     if [ -t 2 ]; then
@@ -107,9 +104,11 @@ main() {
     ensure chmod u+x "$_file"
     if [ ! -x "$_file" ]; then
         printf '%s\n' "Cannot execute $_file (likely because of mounting /tmp as noexec)." 1>&2
-        printf '%s\n' "Please copy the file to a location where you can execute binaries and run ./rustup-init${_ext}." 1>&2
+        printf '%s\n' "Please copy the file to a location where you can execute binaries and run ./rustup-init$_ext." 1>&2
         exit 1
     fi
+
+
 
     if [ "$need_tty" = "yes" ]; then
         # The installer is going to want to ask for confirmation by
@@ -141,8 +140,7 @@ get_bitness() {
     #   0x02 for 64-bit.
     # The printf builtin on some shells like dash only supports octal
     # escape sequences, so we use those.
-    local _current_exe_head
-    _current_exe_head=$(head -c 5 /proc/self/exe )
+    local _current_exe_head=$(head -c 5 /proc/self/exe )
     if [ "$_current_exe_head" = "$(printf '\177ELF\001')" ]; then
         echo 32
     elif [ "$_current_exe_head" = "$(printf '\177ELF\002')" ]; then
@@ -161,8 +159,7 @@ get_endianness() {
     need_cmd head
     need_cmd tail
 
-    local _current_exe_endianness
-    _current_exe_endianness="$(head -c 6 /proc/self/exe | tail -c 1)"
+    local _current_exe_endianness="$(head -c 6 /proc/self/exe | tail -c 1)"
     if [ "$_current_exe_endianness" = "$(printf '\001')" ]; then
         echo "${cputype}${suffix_el}"
     elif [ "$_current_exe_endianness" = "$(printf '\002')" ]; then
@@ -173,51 +170,51 @@ get_endianness() {
 }
 
 get_architecture() {
-    local _ostype _cputype _bitness _arch
-    _ostype="$(uname -s)"
-    _cputype="$(uname -m)"
+
+    local _ostype="$(uname -s)"
+    local _cputype="$(uname -m)"
 
     if [ "$_ostype" = Linux ]; then
         if [ "$(uname -o)" = Android ]; then
-            _ostype=Android
+            local _ostype=Android
         fi
     fi
 
-    if [ "$_ostype" = Darwin ] && [ "$_cputype" = i386 ]; then
-        # Darwin `uname -m` lies
+    if [ "$_ostype" = Darwin -a "$_cputype" = i386 ]; then
+        # Darwin `uname -s` lies
         if sysctl hw.optional.x86_64 | grep -q ': 1'; then
-            _cputype=x86_64
+            local _cputype=x86_64
         fi
     fi
 
     case "$_ostype" in
 
         Android)
-            _ostype=linux-android
+            local _ostype=linux-android
             ;;
 
         Linux)
-            _ostype=unknown-linux-gnu
+            local _ostype=unknown-linux-gnu
             ;;
 
         FreeBSD)
-            _ostype=unknown-freebsd
+            local _ostype=unknown-freebsd
             ;;
 
         NetBSD)
-            _ostype=unknown-netbsd
+            local _ostype=unknown-netbsd
             ;;
 
         DragonFly)
-            _ostype=unknown-dragonfly
+            local _ostype=unknown-dragonfly
             ;;
 
         Darwin)
-            _ostype=apple-darwin
+            local _ostype=apple-darwin
             ;;
 
         MINGW* | MSYS* | CYGWIN*)
-            _ostype=pc-windows-gnu
+            local _ostype=pc-windows-gnu
             ;;
 
         *)
@@ -229,71 +226,72 @@ get_architecture() {
     case "$_cputype" in
 
         i386 | i486 | i686 | i786 | x86)
-            _cputype=i686
+            local _cputype=i686
             ;;
 
         xscale | arm)
-            _cputype=arm
+            local _cputype=arm
             if [ "$_ostype" = "linux-android" ]; then
-                _ostype=linux-androideabi
+                local _ostype=linux-androideabi
             fi
             ;;
 
         armv6l)
-            _cputype=arm
+            local _cputype=arm
             if [ "$_ostype" = "linux-android" ]; then
-                _ostype=linux-androideabi
+                local _ostype=linux-androideabi
             else
-                _ostype="${_ostype}eabihf"
+                local _ostype="${_ostype}eabihf"
             fi
             ;;
 
         armv7l | armv8l)
-            _cputype=armv7
+            local _cputype=armv7
             if [ "$_ostype" = "linux-android" ]; then
-                _ostype=linux-androideabi
+                local _ostype=linux-androideabi
             else
-                _ostype="${_ostype}eabihf"
+                local _ostype="${_ostype}eabihf"
             fi
             ;;
 
         aarch64)
-            _cputype=aarch64
+            local _cputype=aarch64
             ;;
 
         x86_64 | x86-64 | x64 | amd64)
-            _cputype=x86_64
+            local _cputype=x86_64
             ;;
 
         mips)
-            _cputype="$(get_endianness $_cputype "" 'el')"
+            local _cputype="$(get_endianness $_cputype "" 'el')"
             ;;
 
         mips64)
-            _bitness="$(get_bitness)"
-            if [ "$_bitness" -eq 32 ]; then
-                if [ "$_ostype" = "unknown-linux-gnu" ]; then
+            local _bitness="$(get_bitness)"
+            if [ $_bitness = "32" ]; then
+                if [ $_ostype = "unknown-linux-gnu" ]; then
                     # 64-bit kernel with 32-bit userland
                     # endianness suffix is appended later
-                    _cputype=mips
+                    local _cputype=mips
                 fi
             else
                 # only n64 ABI is supported for now
-                _ostype="${_ostype}abi64"
+                local _ostype="${_ostype}abi64"
             fi
-            _cputype="$(get_endianness "$_cputype" "" 'el')"
+
+            local _cputype="$(get_endianness $_cputype "" 'el')"
             ;;
 
         ppc)
-            _cputype=powerpc
+            local _cputype=powerpc
             ;;
 
         ppc64)
-            _cputype=powerpc64
+            local _cputype=powerpc64
             ;;
 
         ppc64le)
-            _cputype=powerpc64le
+            local _cputype=powerpc64le
             ;;
 
         *)
@@ -301,37 +299,30 @@ get_architecture() {
 
     esac
 
-    # Detect 64-bit linux with 32-bit userland for x86
-    if [ "$_ostype" = unknown-linux-gnu ] && [ "$_cputype" = x86_64 ]; then
+    # Detect 64-bit linux with 32-bit userland
+    if [ $_ostype = unknown-linux-gnu -a $_cputype = x86_64 ]; then
         if [ "$(get_bitness)" = "32" ]; then
-            _cputype=i686
-        fi
-    fi
-
-    # Detect 64-bit linux with 32-bit userland for powerpc
-    if [ $_ostype = unknown-linux-gnu ] && [ $_cputype = powerpc64 ]; then
-        if [ "$(get_bitness)" = "32" ]; then
-            local _cputype=powerpc
+            local _cputype=i686
         fi
     fi
 
     # Detect armv7 but without the CPU features Rust needs in that build,
     # and fall back to arm.
     # See https://github.com/rust-lang/rustup.rs/issues/587.
-    if [ "$_ostype" = "unknown-linux-gnueabihf" ] && [ "$_cputype" = armv7 ]; then
+    if [ $_ostype = "unknown-linux-gnueabihf" -a $_cputype = armv7 ]; then
         if ensure grep '^Features' /proc/cpuinfo | grep -q -v neon; then
             # At least one processor does not have NEON.
-            _cputype=arm
+            local _cputype=arm
         fi
     fi
 
-    _arch="${_cputype}-${_ostype}"
+    local _arch="$_cputype-$_ostype"
 
     RETVAL="$_arch"
 }
 
 say() {
-    printf 'rustup: %s\n' "$1"
+    echo "rustup: $1"
 }
 
 err() {
@@ -340,17 +331,18 @@ err() {
 }
 
 need_cmd() {
-    if ! check_cmd "$1"; then
-        err "need '$1' (command not found)"
+    if ! check_cmd "$1"
+    then err "need '$1' (command not found)"
     fi
 }
 
 check_cmd() {
     command -v "$1" > /dev/null 2>&1
+    return $?
 }
 
 need_ok() {
-    if [ $? -ne 0 ]; then err "$1"; fi
+    if [ $? != 0 ]; then err "$1"; fi
 }
 
 assert_nz() {
@@ -375,23 +367,20 @@ ignore() {
 # This wraps curl or wget. Try curl first, if not installed,
 # use wget instead.
 downloader() {
-    local _dld
-    if check_cmd curl; then
-        _dld=curl
-    elif check_cmd wget; then
-        _dld=wget
-    else
-        _dld='curl or wget' # to be used in error message of need_cmd
+    if check_cmd curl
+    then _dld=curl
+    elif check_cmd wget
+    then _dld=wget
+    else _dld='curl or wget' # to be used in error message of need_cmd
     fi
 
-    if [ "$1" = --check ]; then
-        need_cmd "$_dld"
-    elif [ "$_dld" = curl ]; then
-        curl -sSfL "$1" -o "$2"
-    elif [ "$_dld" = wget ]; then
-        wget "$1" -O "$2"
-    else
-        err "Unknown downloader"   # should not reach here
+    if [ "$1" = --check ]
+    then need_cmd "$_dld"
+    elif [ "$_dld" = curl ]
+    then curl -sSfL "$1" -o "$2"
+    elif [ "$_dld" = wget ]
+    then wget "$1" -O "$2"
+    else err "Unknown downloader"   # should not reach here
     fi
 }
 
