Update externals
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/rust/scripts/rustup b/rust/scripts/rustup
--- a/rust/scripts/rustup
+++ b/rust/scripts/rustup
@@ -1,28 +1,18 @@
 #!/bin/bash
-# Copyright 2016 The Rust Project Developers. See the COPYRIGHT
-# file at the top-level directory of this distribution and at
-# http://rust-lang.org/COPYRIGHT.
-#
-# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
-# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
-# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
-# option. This file may not be copied, modified, or distributed
-# except according to those terms.
 
 # This is just a little script that can be downloaded from the internet to
 # install rustup. It just does platform detection, downloads the installer
 # and runs it.
 
-if [ -z "$RUSTUP_UPDATE_ROOT" ]; then
-    RUSTUP_UPDATE_ROOT="https://static.rust-lang.org/rustup"
-fi
-
 set -u
+
+# If RUSTUP_UPDATE_ROOT is unset or empty, default it.
+RUSTUP_UPDATE_ROOT="${RUSTUP_UPDATE_ROOT:-https://static.rust-lang.org/rustup}"
 
 #XXX: If you change anything here, please make the same changes in setup_mode.rs
 usage() {
     cat 1>&2 <<EOF
-rustup-init 1.17.0 (edb52ac60 2019-03-05)
+rustup-init 1.18.0 (bb84b5d85 2019-04-22)
 The installer for rustup
 
 USAGE:
@@ -198,6 +188,7 @@ get_architecture() {
 
         Linux)
             _ostype=unknown-linux-gnu
+            _bitness=$(get_bitness)
             ;;
 
         FreeBSD)
@@ -266,22 +257,15 @@ get_architecture() {
             ;;
 
         mips)
-            _cputype="$(get_endianness $_cputype "" 'el')"
+            _cputype=$(get_endianness mips '' el)
             ;;
 
         mips64)
-            _bitness="$(get_bitness)"
-            if [ "$_bitness" -eq 32 ]; then
-                if [ "$_ostype" = "unknown-linux-gnu" ]; then
-                    # 64-bit kernel with 32-bit userland
-                    # endianness suffix is appended later
-                    _cputype=mips
-                fi
-            else
+            if [ "$_bitness" -eq 64 ]; then
                 # only n64 ABI is supported for now
                 _ostype="${_ostype}abi64"
+                _cputype=$(get_endianness mips64 '' el)
             fi
-            _cputype="$(get_endianness "$_cputype" "" 'el')"
             ;;
 
         ppc)
@@ -301,18 +285,19 @@ get_architecture() {
 
     esac
 
-    # Detect 64-bit linux with 32-bit userland for x86
-    if [ "$_ostype" = unknown-linux-gnu ] && [ "$_cputype" = x86_64 ]; then
-        if [ "$(get_bitness)" = "32" ]; then
-            _cputype=i686
-        fi
-    fi
-
-    # Detect 64-bit linux with 32-bit userland for powerpc
-    if [ $_ostype = unknown-linux-gnu ] && [ $_cputype = powerpc64 ]; then
-        if [ "$(get_bitness)" = "32" ]; then
-            local _cputype=powerpc
-        fi
+    # Detect 64-bit linux with 32-bit userland
+    if [ "${_ostype}" = unknown-linux-gnu ] && [ "${_bitness}" -eq 32 ]; then
+        case $_cputype in
+            x86_64)
+                _cputype=i686
+                ;;
+            mips64)
+                _cputype=$(get_endianness mips '' el)
+                ;;
+            powerpc64)
+                _cputype=powerpc
+                ;;
+        esac
     fi
 
     # Detect armv7 but without the CPU features Rust needs in that build,
@@ -349,10 +334,6 @@ check_cmd() {
     command -v "$1" > /dev/null 2>&1
 }
 
-need_ok() {
-    if [ $? -ne 0 ]; then err "$1"; fi
-}
-
 assert_nz() {
     if [ -z "$1" ]; then err "assert_nz $2"; fi
 }
@@ -361,8 +342,7 @@ assert_nz() {
 # will immediately terminate with an error showing the failing
 # command.
 ensure() {
-    "$@"
-    need_ok "command failed: $*"
+    if ! "$@"; then err "command failed: $*"; fi
 }
 
 # This is just for indicating that commands' results are being
@@ -387,9 +367,9 @@ downloader() {
     if [ "$1" = --check ]; then
         need_cmd "$_dld"
     elif [ "$_dld" = curl ]; then
-        curl -sSfL "$1" -o "$2"
+        curl --proto '=https' --tlsv1.2 --silent --show-error --fail --location "$1" --output "$2"
     elif [ "$_dld" = wget ]; then
-        wget "$1" -O "$2"
+        wget --https-only --secure-protocol=TLSv1_2 "$1" -O "$2"
     else
         err "Unknown downloader"   # should not reach here
     fi
