new-oe-build: explicitly error and return if setup script fails
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/bitbake/zsh-functions/new-oe-build b/bitbake/zsh-functions/new-oe-build
--- a/bitbake/zsh-functions/new-oe-build
+++ b/bitbake/zsh-functions/new-oe-build
@@ -70,7 +70,10 @@ fi
             . ../meta-sokol-flex/setup-environment -b . $args ${MACHINE:-qemuarm64}
         else
             . ../meta-mentor/setup-environment -b . $args ${MACHINE:-qemuarm64}
-        fi
+        fi || {
+            echo >&2 "Error: setup-environment failed"
+            return 1
+        }
     elif [[ -n "$imx" ]]; then
         case "$(cd "$BUILDDIR" && pwd -P)" in
             "$(cd "$topdir" && pwd -P)/"*)
