zsh: check for ATT_ENV in att-*env functions
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/zsh/functions/att-env b/zsh/functions/att-env
--- a/zsh/functions/att-env
+++ b/zsh/functions/att-env
@@ -1,4 +1,8 @@
 # Just for convenience
 att-env () {
+    if [[ -z "$ATT_ENV" ]]; then
+        echo >&2 "Error: ATT_ENV not set, aborting"
+        return 1
+    fi
     cat $ATT_ENV
 }
diff --git a/zsh/functions/att-update-env b/zsh/functions/att-update-env
--- a/zsh/functions/att-update-env
+++ b/zsh/functions/att-update-env
@@ -1,4 +1,8 @@
 att-update-env () {
+    if [[ -z "$ATT_ENV" ]]; then
+        echo >&2 "Error: ATT_ENV not set, aborting"
+        return 1
+    fi
     while IFS== read var value; do
         if [[ $var = -* ]]; then
             unset ${var/-}
