bootstrap: also symlink DOTFILES_DIR to ~/.dotfiles

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -160,17 +160,22 @@ if ! [ -e "$DOTFILES_DIR" ]; then
     run git clone --recursive https://github.com/kergoth/dotfiles "$DOTFILES_DIR"
 fi
 
-if ! [ -h ~/.local/share/chezmoi ]; then
-    # Symlink to ~/.local/share/chezmoi to let chezmoi find the hook scripts
-    if [ -h ~/.local/share/chezmoi ]; then
-        rm -f ~/.local/share/chezmoi
-    elif [ -e ~/.local/share/chezmoi ]; then
-        echo >&2 "Error: ~/.local/share/chezmoi exists and is not a symlink"
-        exit 1
+for subdir in ~/.local/share/chezmoi ~/.dotfiles; do
+    if [ "$subdir" = "$DOTFILES_DIR" ]; then
+        continue
     fi
-    mkdir -p ~/.local/share
-    ln -sf "$DOTFILES_DIR" ~/.local/share/chezmoi
-fi
+    if ! [ -h "$subdir" ]; then
+        # Symlink to ~/.local/share/chezmoi to let chezmoi find the hook scripts
+        if [ -h "$subdir" ]; then
+            rm -f "$subdir"
+        elif [ -e "$subdir" ]; then
+            echo >&2 "Error: $subdir exists and is not a symlink"
+            exit 1
+        fi
+        mkdir -p "$(dirname "$subdir")"
+        ln -sf "$DOTFILES_DIR" "$subdir"
+    fi
+done
 
 if ! command -v chezmoi >/dev/null 2>&1; then
     echo >&2 "Installing chezmoi"
