bootstrap: check for chezmoiroot after clone, not before

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -151,13 +151,14 @@ if [ -z "${DOTFILES_DIR:-}" ]; then
         fi
     fi
 fi
-if ! [ -e "$DOTFILES_DIR/.chezmoiroot" ]; then
-    echo >&2 "Error: DOTFILES_DIR $DOTFILES_DIR is not a chezmoi repository, exiting"
-    exit 1
-fi
 
 if ! [ -e "$DOTFILES_DIR" ]; then
     run git clone --recursive https://github.com/kergoth/dotfiles "$DOTFILES_DIR"
+fi
+
+if ! [ -e "$DOTFILES_DIR/.chezmoiroot" ]; then
+    echo >&2 "Error: DOTFILES_DIR $DOTFILES_DIR is not a chezmoi repository, exiting"
+    exit 1
 fi
 
 for subdir in ~/.local/share/chezmoi ~/.dotfiles; do
