Stop overriding peru state dir
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/script/dotfiles-external-update b/script/dotfiles-external-update
--- a/script/dotfiles-external-update
+++ b/script/dotfiles-external-update
@@ -22,8 +22,8 @@ if ! which peru >/dev/null 2>&1; then
 fi
 PATH="$PATH:${XDG_DATA_HOME:-$HOME/.local/share}/../bin"
 
-"$dotfilesdir/script/peru" reup -f || echo >&2 "peru reup failed"
-"$dotfilesdir/script/peru" sync -f || die "peru sync failed"
+peru reup -f || echo >&2 "peru reup failed"
+peru sync -f || die "peru sync failed"
 
 if [ -e vscode/zsh-functions/_code ]; then
     sed -i.bak -e 's/@@APPNAME@@/code/' vscode/zsh-functions/_code
