First pass attempt at vimtogitcolors.

diff --git a/.sh/firstinteractive b/.sh/firstinteractive
--- a/.sh/firstinteractive
+++ b/.sh/firstinteractive
@@ -1,13 +1,89 @@
+normalcode=`cat $HOME/.vimcolors|grep "^normalfg "|sed -e"s,^normalfg ,,"`
+normalfg=""
+codetogitcolor () {
+    code="$1"
+    state=""
+    attr=""
+    fg=""
+    bg=""
+    for i in `echo $code | sed -e's,\;, ,g'`; do
+        if [ "$state" = "fg" ]; then
+            if [ "$i" = "5" ]; then
+                continue
+            else
+                fg=$i
+                state=""
+            fi
+        elif [ "$state" = "bg" ]; then
+            if [ "$i" = "5" ]; then
+                continue
+            else
+                bg=$i
+                state=""
+            fi
+        else
+            if [ $i = "38" ]; then
+                state="fg"
+            elif [ $i = "48" ]; then
+                state="bg"
+            elif [ $i = "1" ]; then # bold
+                attr="bold"
+            elif [ $i = "7" ]; then
+                attr="reverse"
+            fi
+            continue
+        fi
+    done
+
+    val=""
+    if [ -n "$fg" ]; then
+        val="$fg"
+        if [ -n "$bg" ]; then
+            val="$val $bg"
+        fi
+        if [ -n "$attr" ]; then
+            val="$val $attr"
+        fi
+    elif [ -n "$bg" -a -n "$normalfg" ]; then
+        val="$normalfg $bg"
+        if [ -n "$attr" ]; then
+            val="$val $attr"
+        fi
+    elif [ -n "$attr" ]; then
+        val="$attr"
+    fi
+    echo "$val"
+}
+normalfg=`codetogitcolor "$normalcode"|sed -e's, .*$,,'`
+if [ -z "$normalfg" ]; then
+    normalfg="white"
+fi
+
 if [ "$PS1" -a -n "$TERM" ]; then
     if [ -r "$HOME/.vim/vimcolorcodes.vim" ]; then
         vim --noplugin -c "so $HOME/.vim/vimcolorcodes.vim | quit" >/dev/null 2>&1
     fi
     if [ -e $HOME/.vimcolors ]; then
         if [ -e $HOME/.vimtodircolors ]; then
-            cat .vimtodircolors | grep -v "^#" | while read dircolor higrp; do
+            cat $HOME/.vimtodircolors | grep -v "^#" | while read dircolor higrp; do
                 code=`cat $HOME/.vimcolors|grep "^$higrp "|sed -e"s,^$higrp ,,"`
                 echo $dircolor $code
             done > $HOME/.dir_colors
+        fi
+        if [ -e $HOME/.vimtogitcolors ]; then
+#            git-config --global $param $value
+            while read param higrp; do
+                if [ -z "$param" ] || echo "$param" | grep -q "^#"; then
+                    continue
+                fi
+                code=`cat $HOME/.vimcolors|grep "^$higrp "|sed -e"s,^$higrp ,,"`
+                gitcolor=`codetogitcolor "$code"`
+                if [ -z "$gitcolor" ]; then
+                    echo >&2 "Unable to determine git color for highlight group $higrp."
+                else
+                    git config --global --replace-all $param "$gitcolor"
+                fi
+            done < $HOME/.vimtogitcolors
         fi
     fi
 
@@ -26,20 +102,8 @@ if [ "$PS1" -a -n "$TERM" ]; then
                     GREP_COLORS="$cap=$code"
                 fi
             done < $HOME/.vimtogrepcolors
-#            cat .vimtogrepcolors | grep -v "^#" | while read cap higrp; do
-#                echo $cap=$higrp
-#                code=`cat $HOME/.vimcolors|grep "^$higrp "|sed -e"s,^$higrp ,,"`
-#                if [ -n "$GREP_COLORS" ]; then
-#                    GREP_COLORS="$GREP_COLORS:$cap=$code"
-#                else
-#                    GREP_COLORS="$cap=$code"
-#                fi
-#                echo $GREP_COLORS
-#            done
-            echo $GREP_COLORS
         fi
     fi
-    echo whee $GREP_COLORS
     export GREP_OPTIONS GREP_COLORS
 
     if [ -e "$HOME/.dir_colors" ]; then
