att: error if too many args are passed
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/att b/scripts/att
--- a/scripts/att
+++ b/scripts/att
@@ -40,6 +40,11 @@ fi
 
 if [ $# -lt 1 ]; then
     list_sessions
+elif [ $# -gt 1 ]; then
+    echo >&2 "Error: too many arguments"
+    echo >&2
+    echo >&2 "Usage: ${0##*/} [SESSION_NAME]"
+    exit 2
 else
     if [ -n "$ATT_SESSION" ]; then
         echo >&2 "att: already inside an att session"
