ddimage-sd: align with bmaptool-sd
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/scripts/ddimage-sd b/scripts/ddimage-sd
--- a/scripts/ddimage-sd
+++ b/scripts/ddimage-sd
@@ -1,6 +1,8 @@
 #!/bin/sh
 # OSX-only script to run ddimage against the internal SD Card Reader on a Mac
 
+set -u
+
 get_sdcard_device () {
     diskutil list | sed -n '/^\/dev\/disk/s/ (internal, physical)://p' | \
         grep -v '/dev/disk0$' | while read -r disk; do
@@ -12,22 +14,29 @@ get_sdcard_device () {
     return 1
 }
 
-sdcard_device="$(get_sdcard_device)"
-if [ $? -ne 0 ]; then
-    echo >&2 "Error: no SD Card Reader found"
-    return 1
+if [ $# -ne 1 ]; then
+    echo >&2 "Usage: ${0##*/} IMAGE_FILE"
+    exit 2
 fi
 
-diskutil unmountDisk "$sdcard_device" || return $?
+sdcard_device="$(get_sdcard_device)"
+if [ -z "$sdcard_device" ]; then
+    echo >&2 "Error: no SD Card Reader found"
+    exit 1
+fi
 
+diskutil list "$sdcard_device"
+diskutil unmountDisk "$sdcard_device" || exit $?
+
+rdevice="/dev/r${sdcard_device#/dev/}"
 if [ "$sdcard_device" = "/dev/disk1" ]; then
     # ddimage is picky, excluding disk0 & disk1, but disk1 as the SD card
     # reader is valid on some Macs.
     if which pv >/dev/null 2>&1; then
-        pv "$1" | sudo dd of="/dev/r${sdcard_device#/dev/}" bs="1m"
+        pv "$1" | sudo dd of="$rdevice" bs="1m"
     else
-        sudo dd if="$1" of="/dev/r${sdcard_device#/dev/}" bs="1m"
+        sudo dd if="$1" of="$rdevice" bs="1m"
     fi
 else
-    sudo ddimage "$1" "/dev/r${sdcard_device#/dev/}"
+    sudo ddimage "$1" "$rdevice"
 fi
