dotfiles-external-update: don't exit on reup failure, so we get ack2/gist update
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/scripts/dotfiles-external-update b/scripts/dotfiles-external-update
--- a/scripts/dotfiles-external-update
+++ b/scripts/dotfiles-external-update
@@ -22,7 +22,7 @@ if ! which peru >/dev/null 2>&1; then
 fi
 PATH="$PATH:${XDG_DATA_HOME:-~/.local/share}/../bin"
 
-peru reup || die "peru reup failed"
+peru reup || echo >&2 "peru reup failed"
 peru sync -f || die "peru sync failed"
 
 cd "$tmpdir"
