iln: fix -r sanity check when nothing is in common
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/scripts/iln b/scripts/iln
--- a/scripts/iln
+++ b/scripts/iln
@@ -213,13 +213,18 @@ ln () {
         target="$(abspath "$target")"
         targetdir="${target%/*}"
         source="$(relpath "$targetdir" "$source")"
-
-        # Sanity check
-        resolved_path="$(normalize_path "$targetdir/$source")"
-        if [ ! -e "$resolved_path" ]; then
-            echo >&2 "Error: $resolved_path does not exist"
-            return 1
-        fi
+        case "$source" in
+            /*)
+                ;;
+            *)
+                # Sanity check
+                resolved_path="$(normalize_path "$targetdir/$source")"
+                if [ ! -e "$resolved_path" ]; then
+                    echo >&2 "Error: $resolved_path does not exist"
+                    return 1
+                fi
+                ;;
+        esac
     fi
 
     if [ $create_leading_dirs -eq 1 ]; then
