install-brew: add arg to separate prefix/repo
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/scripts/install-brew b/scripts/install-brew
--- a/scripts/install-brew
+++ b/scripts/install-brew
@@ -2,21 +2,63 @@
 
 set -eu
 
+usage () {
+    echo >&2 "${0##*/} [-h|-s] INSTALL_PATH"
+    echo >&2
+    echo >&2 "Install homebrew to the specified INSTALL_PATH"
+    echo >&2
+    echo >&2 "Options:"
+    echo >&2
+    echo >&2 "  -s          Separate the prefix and repo."
+    echo >&2 "  -h          Show this help."
+    exit 2
+}
+
+separate_prefix=0
+while getopts sh opt; do
+    case "$opt" in
+        s)
+            separate_prefix=1
+            ;;
+        \?|h)
+            usage
+            ;;
+    esac
+done
+shift $((OPTIND - 1))
+
+if [ $# -ne 1 ]; then
+    usage
+fi
+
 mkdir -p "$1"
-HOMEBREW_PATH="$(cd "$1" && pwd -P)"
-PATH="$HOMEBREW_PATH/bin:$PATH"
+HOMEBREW_PREFIX="$(cd "$1" && pwd -P)"
+PATH="$HOMEBREW_PREFIX/bin:$PATH"
 
-mkdir -p "$HOMEBREW_PATH" && \
+if [ $separate_prefix -eq 1 ]; then
+    HOMEBREW_REPO="$HOMEBREW_PREFIX/homebrew"
+    mkdir -p "$HOMEBREW_PREFIX/bin"
+    ln -sf ../homebrew/bin/brew "$HOMEBREW_PREFIX/bin/brew"
+else
+    HOMEBREW_REPO="$HOMEBREW_PREFIX"
+fi
+
+mkdir -p "$HOMEBREW_REPO" && \
     curl -sSfL https://github.com/Homebrew/homebrew/tarball/master | \
-        tar xz --strip 1 -C "$HOMEBREW_PATH"
+        tar xz --strip 1 -C "$HOMEBREW_REPO"
 
-if [ "$(brew --prefix)" != "$HOMEBREW_PATH" ]; then
-    printf >&2 "Error: brew prefix %s does not match the specified %s" "$(brew --prefix)" "$HOMEBREW_PATH"
+if [ "$(brew --prefix)" != "$HOMEBREW_PREFIX" ]; then
+    printf >&2 "Error: brew prefix %s does not match the specified %s" "$(brew --prefix)" "$HOMEBREW_PREFIX"
     exit 1
 fi
 
-if [ -d "$HOMEBREW_PATH/share/doc/homebrew" ]; then
-    rm -rf "$HOMEBREW_PATH/share/doc/homebrew"
+if [ "$(brew --repo)" != "$HOMEBREW_REPO" ]; then
+    printf >&2 "Error: brew repo %s does not match the specified %s" "$(brew --repo)" "$HOMEBREW_REPO"
+    exit 1
+fi
+
+if [ -d "$HOMEBREW_PREFIX/share/doc/homebrew" ]; then
+    rm -rf "$HOMEBREW_PREFIX/share/doc/homebrew"
 fi
 brew update || exit 2
 
