pipv{,3}: error if venv name starts with -
Occasionally I forget the venv name and just start passing pip options, and
end up cluttered up with badly named virtualenvs.

Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/scripts/pipv b/scripts/pipv
--- a/scripts/pipv
+++ b/scripts/pipv
@@ -19,6 +19,13 @@ fi
 
 venv="$1"
 shift
+case "$venv" in
+    -*)
+        echo >&2 "Error: venv starts with -: $venv"
+        exit 1
+        ;;
+esac
+
 venv_dir="$WORKON_HOME/$venv"
 if [ ! -e "$venv_dir" ]; then
     virtualenv "$venv_dir"
diff --git a/scripts/pipv3 b/scripts/pipv3
--- a/scripts/pipv3
+++ b/scripts/pipv3
@@ -16,6 +16,13 @@ if [ $# -eq 0 ]; then
 fi
 
 venv="$1"
+case "$venv" in
+    -*)
+        echo >&2 "Error: venv starts with -: $venv"
+        exit 1
+        ;;
+esac
+
 venv_dir="$WORKON_HOME/$venv"
 if [ ! -e "$venv_dir" ]; then
     pyvenv "$venv_dir"
