arch: skip multi-user pacman-based nix setup if systemd isn't running

diff --git a/scripts/setup-system-arch.tmpl b/scripts/setup-system-arch.tmpl
--- a/scripts/setup-system-arch.tmpl
+++ b/scripts/setup-system-arch.tmpl
@@ -55,25 +55,24 @@ fi
 
 pacman_install vi zsh which xz
 
-{{ if and .use_nix (not .wsl2) .has_init -}}
-if ! has nix; then
-    pacman_install nix
-fi
-
-if ! grep -q "^nix-users:.*$USER" /etc/group; then
-    sudorun sed -i -e "/^nix-users:/s/\$/ $USER/; /^nix-users:/s/: /:/;" /etc/group
-    if ! grep -q "^nix-users:.*$USER" /etc/group; then
-        echo >&2 "Failed to add user to the nix-users group, please do so manually, then re-login"
-    else
-        echo >&2 "User has been added to the nix-users group, please re-login"
-    fi
-fi
-
+{{ if and .use_nix (not .wsl2) -}}
 if pgrep systemd >/dev/null 2>&1; then
+    # systemd is running: use pacman nix (multi-user daemon approach)
+    if ! has nix; then
+        pacman_install nix
+    fi
+
+    if ! grep -q "^nix-users:.*$USER" /etc/group; then
+        sudorun sed -i -e "/^nix-users:/s/\$/ $USER/; /^nix-users:/s/: /:/;" /etc/group
+        if ! grep -q "^nix-users:.*$USER" /etc/group; then
+            echo >&2 "Failed to add user to the nix-users group, please do so manually, then re-login"
+        else
+            echo >&2 "User has been added to the nix-users group, please re-login"
+        fi
+    fi
+
     sudorun systemctl enable nix-daemon
     sudorun systemctl start nix-daemon
-else
-    echo >&2 "Warning: no systemd running, unable to start nix daemon"
 fi
 {{- end }}
 
