setup-user-steamos: set up retrodeck/texture_packs/Flycast
Note: I need to submit this as an issue to RetroDeck.

diff --git a/scripts/setup-user-steamos.tmpl b/scripts/setup-user-steamos.tmpl
--- a/scripts/setup-user-steamos.tmpl
+++ b/scripts/setup-user-steamos.tmpl
@@ -213,3 +213,24 @@ if [ -d ~/homebrew ]; then
         fi
     fi
 fi
+
+if [ -d "$sdmount/retrodeck" ]; then
+    # Set up retrodeck/texture_packs/Flycast
+    #   FIXME: Submit this as an issue to RetroDeck
+    #   Note: This will only work if I run this after RetroDeck has been run once to set it up.
+    bios_dir="$sdmount/retrodeck/bios/dc/textures"
+    texture_dir="$sdmount/retrodeck/texture_packs/Flycast"
+    if [ -d "$bios_dir" ] && ! [ -L "$bios_dir" ]; then
+        if [ -d "$texture_dir" ]; then
+            echo >&2 "Error: both retrodeck/texture_packs/Flycast and retrodeck/bios/dc/textures exist"
+        else
+            echo >&2 "Moving existing retrodeck/bios/dc/textures to retrodeck/texture_packs/Flycast"
+            mv "$bios_dir" "$texture_dir"
+        fi
+    fi
+    if ! [ -e "$bios_dir" ]; then
+        mkdir -p "$texture_dir"
+        rm -f "$bios_dir"
+        ln -srf "$texture_dir" "$bios_dir"
+    fi
+fi
