Add a fallback apply for externals to setup-user-linux

diff --git a/scripts/setup-user-linux.tmpl b/scripts/setup-user-linux.tmpl
--- a/scripts/setup-user-linux.tmpl
+++ b/scripts/setup-user-linux.tmpl
@@ -108,6 +108,11 @@ fi
 # Dotfiles
 if [ -z "${CHEZMOI:-}" ]; then
     "$repodir/script/setup" || ret=$?
+    if ! [ -e ~/.local/bin/uv ]; then
+        # If the chezmoi apply failed due to a script or the like, we could end
+        # up without our externals. Explicitly attempt to apply those.
+        chezmoi apply ~/.local/bin ||language ret=$?
+    fi
 fi
 
 {{- if and .user_setup (not .use_nix) -}}
