setup-user-linux: reorganize a bit

diff --git a/scripts/setup-user-linux.tmpl b/scripts/setup-user-linux.tmpl
--- a/scripts/setup-user-linux.tmpl
+++ b/scripts/setup-user-linux.tmpl
@@ -12,6 +12,23 @@ trap 'rm -rf "$tmpdir"' EXIT INT TERM
 # shellcheck source=./common.sh
 . "$scriptdir/common.sh" || exit 1
 
+eget_install() {
+    local repo="$1"
+    shift
+    local cmd="${1:-$(basename "$repo")}"
+    shift
+
+    if [ ! -e "$HOME/.local/bin/$cmd" ]; then
+        echo >&2 "Installing $cmd via $repo"
+        if eget -a '^gnu' --to="$tmpdir/$cmd" "$@" "$repo"; then
+            mv "$tmpdir/$cmd" "$HOME/.local/bin/$cmd"
+        else
+            echo >&2 "Error downloading and installing $cmd via $repo"
+            return 1
+        fi
+    fi
+}
+
 ret=0
 
 # Dotfiles
@@ -35,8 +52,8 @@ fi
         mv eget ~/.local/bin/
     fi
 
-    # Install gget
     if ! [ -e ~/.local/bin/gget ]; then
+        # Install gget
         curl -Lo gget https://github.com/dpb587/gget/releases/download/v0.6.1/gget-0.6.1-linux-amd64 &&
             echo "d1c92e0e28576876bd46d3689b50c0f31df45299  gget" |
             shasum -c && \
@@ -44,29 +61,7 @@ fi
         mv gget ~/.local/bin/
     fi
 
-
-    # Can't install via release binary
-    # unar
-    # zstd
-    # patchutils
-    # sapling
-
-    eget_install() {
-        local repo="$1"
-        shift
-        local cmd="${1:-$(basename "$repo")}"
-        shift
-
-        if [ ! -e "$HOME/.local/bin/$cmd" ]; then
-            echo >&2 "Installing $cmd via $repo"
-            if eget -a '^gnu' --to="$tmpdir/$cmd" "$@" "$repo"; then
-                mv "$tmpdir/$cmd" "$HOME/.local/bin/$cmd"
-            else
-                echo >&2 "Error downloading and installing $cmd via $repo"
-                return 1
-            fi
-        fi
-    }
+    # Can't install via release binary: unar, zstd, patchutils, sapling
 
     # Core tools
     eget_install direnv/direnv
