setup-user-linux: handle zsh in places other than /bin

diff --git a/scripts/setup-user-linux b/scripts/setup-user-linux
--- a/scripts/setup-user-linux
+++ b/scripts/setup-user-linux
@@ -38,9 +38,12 @@ if chezmoi dump-config 2>/dev/null | grep -q ephemeral.\*true; then
 fi
 
 # User shell should be zsh
-if [ -e /bin/zsh ] && [ "$(getent passwd "$(id -un)" | awk -F : '{print $NF}')" != /bin/zsh ]; then
-    msg "Changing user shell to zsh"
-    # Failure is ignored here, as in some cases the user password might not be
-    # known or set, as is the case with some container usage.
-    chsh -s /bin/zsh || :
+zsh_binary=$(command -v zsh 2>/dev/null) || :
+if [ -n "$zsh_binary" ] && grep -qFx "$zsh_binary" /etc/shells; then
+    if [ "$(getent passwd "$(id -un)" | awk -F : '{print $NF}')" != "$zsh_binary" ]; then
+        msg "Changing user shell to zsh"
+        # Failure is ignored here, as in some cases the user password might not be
+        # known or set, as is the case with some container usage.
+        chsh -s /bin/zsh || :
+    fi
 fi
