split-singles: warn when encountering a duplicated album
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/scripts/split-singles b/scripts/split-singles
--- a/scripts/split-singles
+++ b/scripts/split-singles
@@ -54,9 +54,26 @@ for source_dir; do
                 d="./_Single-Track"
             fi
         fi
-        echo "$dir: $count / $total"
-        mkdir -p "$d/$(dirname "$dir")"
-        rm -f "$d/$dir"
-        ln -rsfv "$dir" "$d/$dir"
+
+        rel="$(relpath "$dir" "$source_dir")"
+        dest="$d/$rel"
+        destdir="$(dirname "$dest")"
+
+        echo "$rel: $count / $total"
+        mkdir -p "$destdir"
+        if [ -h "$dest" ]; then
+            if [ -d "$dest" ]; then
+                olddest="$(cd "$dest" && pwd -P)"
+            else
+                olddest="$(cd "$destdir" && abspath "$(readlink "$(basename "$rel")")")"
+            fi
+            absdir="$(cd "$dir" && pwd -P)"
+            if [ "$olddest" != "$absdir" ]; then
+                echo >&2 "Error: $dest exists but points to $olddest, not $absdir"
+                continue
+            fi
+        fi
+        rm -f "$dest"
+        ln -rsfv "$dir" "$dest"
     done
 done
