Clean up, switch back to zsh, try peru
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/scripts/vipe b/scripts/vipe
--- a/scripts/vipe
+++ b/scripts/vipe
@@ -1,40 +1,76 @@
-#!/usr/bin/env bash
+#!/usr/bin/perl
 
-#
-# vipe(1) - Pipe in and out of $EDITOR
-#
-# (c) 2014 Julian Gruber <julian@juliangruber.com>.
-# MIT licensed.
-#
-# Example:
-#
-#   $ echo foo | vipe | gist
-#   $ vipe | gist
-#
-# This is a lightweight bash only version. For the original impementation in
-# python, check https://github.com/madx/moreutils/blob/master/vipe
-#
+=head1 NAME
 
-# temp file
+vipe - edit pipe
 
-t=/tmp/vipe.$$.txt
-touch $t
+=head1 SYNOPSIS
 
-# read from stdin
+command1 | B<vipe> [...] | command2
 
-if [ ! -t 0 ]; then
-  cat > $t
-fi
+=head1 DESCRIPTION
 
-# spawn editor with stdio connected
+vipe allows you to run your editor in the middle of a unix pipeline and
+edit the data that is being piped between programs. Your editor will
+have the full data being piped from command1 loaded into it, and when you
+save, that data will be piped into command2.
 
-${EDITOR:-vi} $t </dev/tty >/dev/tty || exit $?
+Any extra arguments are passed as arguments to the editor.
 
-# write to stdout
+=head1 ENVIRONMENT VARIABLES
 
-cat $t
+=over 4
 
-# cleanup
+=item EDITOR
 
-rm $t
+Editor to use.
 
+=item VISUAL
+
+Also supported to determine what editor to use.
+
+=back
+
+=head1 AUTHOR
+
+Copyright 2006 by Joey Hess <joey@kitenet.net>
+
+Licensed under the GNU GPL.
+
+=cut
+
+use warnings;
+use strict;
+use File::Temp q{tempfile};
+
+$/=undef;
+
+my ($fh, $tmp)=tempfile();
+die "cannot create tempfile" unless $fh;
+print ($fh <STDIN>) || die "write temp: $!";
+close $fh;
+close STDIN;
+open(STDIN, "</dev/tty") || die "reopen stdin: $!";
+open(OUT, ">&STDOUT") || die "save stdout: $!";
+close STDOUT;
+open(STDOUT, ">/dev/tty") || die "reopen stdout: $!";
+
+my @editor="vi";
+if (-x "/usr/bin/editor") {
+	@editor="/usr/bin/editor";
+}
+if (exists $ENV{EDITOR}) {
+	@editor=split(' ', $ENV{EDITOR});
+}
+if (exists $ENV{VISUAL}) {
+	@editor=split(' ', $ENV{VISUAL});
+}
+my $ret=system(@editor, @ARGV, $tmp);
+if ($ret != 0) {
+	die "@editor exited nonzero, aborting\n";
+}
+
+open (IN, $tmp) || die "$0: cannot read $tmp: $!\n";
+print (OUT <IN>) || die "write failure: $!";
+close IN;
+unlink($tmp);
