github-fetch-forks: accept multiple repos/urls like github-list-forks
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/git/scripts/github-fetch-forks b/git/scripts/github-fetch-forks
--- a/git/scripts/github-fetch-forks
+++ b/git/scripts/github-fetch-forks
@@ -1,19 +1,20 @@
 #!/bin/bash
 
 usage() {
-    echo >&2 "${0##*/} [-a] [URL]"
+    echo >&2 "${0##*/} [options..] [REPO|URL..]"
+    echo >&2
+    echo >&2 "If no REPO/URLs are specified, the url of the ORIGIN_REMOTE is used by default."
     echo >&2
     echo >&2 "Options:"
     echo >&2 "  -a Include all forks of our parent, not just our children."
     echo >&2 "  -o ORIGIN_REMOTE      Prune branches relative to the specified remote, not origin."
     echo >&2 "  -u UPSTREAM_BRANCHES  Specify the base upstream branches where the changes are merged,"
     echo >&2 "                        defaults to master. Comma-separated."
-    echo >&2 "  URL   Github repo URL. If unspecified, the url of the 'origin' git remote is used."
     exit 2
 }
 
 process_arguments () {
-    all=0
+    all=
     origin=origin
     upstream_branches=master
     while getopts ao:u:h opt; do
@@ -33,19 +34,6 @@ process_arguments () {
         esac
     done
     shift $((OPTIND - 1))
-
-    if [ $# -gt 1 ]; then
-        usage
-    elif [ $# -eq 1 ]; then
-        url="$1"
-        shift
-    else
-        url="$(git config remote.$origin.url)"
-        if [ -z "$url" ]; then
-            echo >&2 "Error: no url for the origin git remote"
-            return 1
-        fi
-    fi
 }
 
 set -eu
@@ -53,17 +41,17 @@ set -eu
 process_arguments "$@"
 shift $((OPTIND - 1))
 
-if [ $all -eq 1 ]; then
-    set -- -a
-else
-    set --
-fi
-if [ -n "$url" ]; then
-    set -- "$@" "$url"
+if [ $# -eq 0 ]; then
+    url="$(git config "remote.$origin.url")"
+    if [ -z "$url" ]; then
+        echo >&2 "Error: no url for the origin git remote"
+        return 1
+    fi
+    set -- "$url"
 fi
 
 git fetch "$origin"
-github-list-forks "$@" | while read -r repo; do
+github-list-forks ${all:+-a} "$@" | while read -r repo; do
     remote="${repo%/*}"
     url="https://github.com/$repo"
     if ! git config "remote.$remote.url" >/dev/null; then
