Update externals
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/vim/bundle/polyglot/build b/vim/bundle/polyglot/build
--- a/vim/bundle/polyglot/build
+++ b/vim/bundle/polyglot/build
@@ -52,21 +52,29 @@ extract() {
       fi
     done
 
+    # syntax for go.vim depends on autoload for go.vim, but we exclude the
+    # autoload always and the ftplugin because it's too complex.  FML.
+    if [ "${pack%%:*}" = "go" ]; then
+      copy_file "${dir}${subtree}" "${dir}${subtree}/autoload/go/config.vim" "${name}"
+    fi
+
     output "${subdirs##, })\n"
 
     if (echo "julia coffee-script elixir fish git plantuml scala swift"  | fgrep -q "$name"); then
-	echo "Skipping ftdetect installation of $name"
-	continue
+      echo "Skipping ftdetect installation of $name"
+      continue
     fi
 
-    for f in ${dir}/ftdetect/*; do
-      (
-        echo "augroup filetypedetect";
-        echo '" '"$pack";
-        cat "${f}";
-        echo "augroup END";
-        echo
-      ) >> tmp/polyglot.vim;
+    [ -d "${dir}/ftdetect" ] && for f in "${dir}/ftdetect/"*; do
+      cat <<EOF >> tmp/polyglot.vim
+if !exists('g:polyglot_disabled') || index(g:polyglot_disabled, '${pack%%:*}') == -1
+  augroup filetypedetect
+  " ${pack%%:*}, from ${f##*/ftdetect/} in ${pack#*:}
+$(cat "${f}")
+  augroup end
+endif
+
+EOF
     done
 
   done
@@ -87,18 +95,35 @@ extract() {
 
 copy_dir() {
   for file in $(find "$1/$2" -name '*.vim' -o -name '*.vital'); do
-    file_path="$(dirname "${file##$1/}")"
-    mkdir -p "$file_path"
-    touch "$file_path/$(basename "$file")"
-
-    # Use comma instead of / to handle cases like c/c++
-    sed -e "s,%%PACK%%,$3," -e "/%%CONTENT%%/{r $file" -e "d;}" plugin_guard.vim.template >> $file_path/$(basename "$file")
+    copy_file "$1" "$file" "$3"
   done
 }
 
-update_readme() {
-  OLD_README="$(cat README.md)"
+copy_file() {
+  ## $1 is the build dir (e.g. tmp/vim-go)
+  ## $2 is the full file path, as returned by `find` (e.g. tmp/vim-go/indent/go.vim)
+  ## $3 is the name of the package (so that we can detect if it's disabled at runtime)
+  local tmp_dir="$1"
+  local file_in_tmp="$2"
+  local file_basename="${2##*/}"
+  local file_path="${file_in_tmp##$tmp_dir/}" # Just this file's (full) path
+  file_path="${file_path%/*}"                # Minus the actual name of the file
+  local file_in_dst="${file_path}/${file_basename}" # Could also be ${file_in_tmp##$tmp_dir/}
+  local package_name="$3"
 
+  if [ "${file_in_tmp##$tmp_dir/}" != "${file_in_dst}" ]; then
+    echo "Failure in logic in build script; '${file_in_tmp##$tmp_dir/}' != '${file_in_dst}'.  Bailing." >&2
+    exit 1
+  fi
+
+  mkdir -p "${file_path}"
+  touch "$file_in_dst"
+
+  # Use comma instead of / to handle cases like c/c++
+  sed -e "s,%%PACK%%,${package_name}," -e "/%%CONTENT%%/{r ${file_in_tmp}" -e "d;}" plugin_guard.vim.template >> "$file_in_dst"
+}
+
+update_readme() {
   ed README.md <<- EOF
 /Language packs
 +2kb
@@ -150,6 +175,7 @@ PACKS="
   groovy:vim-scripts/groovy.vim
   haml:sheerun/vim-haml
   handlebars:mustache/vim-mustache-handlebars
+  haproxy:CH-DanReif/haproxy.vim
   haskell:neovimhaskell/haskell-vim
   haxe:yaymukund/vim-haxe
   html5:othree/html5.vim
@@ -207,7 +233,7 @@ PACKS="
   stylus:wavded/vim-stylus
   swift:keith/swift.vim
   sxhkd:baskerville/vim-sxhkdrc
-  systemd:kurayama/systemd-vim-syntax
+  systemd:wgwoods/vim-systemd-syntax
   terraform:hashivim/vim-terraform
   textile:timcharper/textile.vim
   thrift:solarnz/thrift.vim
@@ -231,8 +257,8 @@ rm -rf $DIRS_RM
 mkdir tmp
 
 printf "Downloading packs..."
-download "$PACKS"
-extract "$PACKS"
+download "$(sed '/^#/d' <<<"$PACKS")"
+extract "$(sed '/^#/d' <<<"$PACKS")"
 update_readme
 
 rm -rf tmp
