Update externals
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/fzf/scripts/fzf-tmux b/fzf/scripts/fzf-tmux
--- a/fzf/scripts/fzf-tmux
+++ b/fzf/scripts/fzf-tmux
@@ -179,11 +179,15 @@ trap 'cleanup' EXIT
 
 envs="export TERM=$TERM "
 if [[ "$opt" =~ "-E" ]]; then
-  FZF_DEFAULT_OPTS="--margin 0,1 $FZF_DEFAULT_OPTS"
-  tmux_version=$(tmux -V)
-  if [[ ! $tmux_version =~ 3\.2 ]]; then
+  tmux_version=$(tmux -V | sed 's/[^0-9.]//g')
+  if [[ $(awk '{print ($1 > 3.2)}' <<< "$tmux_version" 2> /dev/null || bc -l <<< "$tmux_version > 3.2") = 1 ]]; then
     FZF_DEFAULT_OPTS="--border $FZF_DEFAULT_OPTS"
     opt="-B $opt"
+  elif [[ $tmux_version = 3.2 ]]; then
+    FZF_DEFAULT_OPTS="--margin 0,1 $FZF_DEFAULT_OPTS"
+  else
+    echo "fzf-tmux: tmux 3.2 or above is required for popup mode" >&2
+    exit 2
   fi
 fi
 [[ -n "$FZF_DEFAULT_OPTS"    ]] && envs="$envs FZF_DEFAULT_OPTS=$(printf %q "$FZF_DEFAULT_OPTS")"
